---
version: "3.8"
networks:
  zeroworks:
    external: true
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    ports:
      - '8080:8080'
    networks:
      - zeroworks
    environment:
      - autoheal=true
      - PUID=1000
      - PGID=1000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    command:
      - "--label-enable"
      - "--cleanup"
      - "--interval=60"
    labels:
      ### Add the below line to every container you want it to watch
      - "com.centurylinklabs.watchtower.enable=true"
